### ISSUE TITLE
Repo only contains localsink element

### ISSUE THREAD

**Issue by michaelfranzl** [MaZderMind/gst-plugin-local#1]
The git repository only contains a "localsink" element. However, `src/NOTES` refers to another element called "localsrc". Perhaps, the files are not yet checked in, or perhaps the README could be updated to give more information about the project or its usage? Thanks.

**Comment by MaZderMind** [comment]
@michaelfranzl This plugin is not implemented yet, it's just ideas and boilerplate. It might be one day, maybe this year; we'll see.
